name: Java CI with Maven
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: ossrh
        server-username: omkart@agsft.com
        server-password: Omkar@774488
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: OmkarT3282
    - name: Deploy with Maven
      run: mvn -B clean deploy -Pci-cd
      env:
        USERNAME: ${{ secrets.OSSRH_USERNAME }}
        PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
